FROM node:latest as build

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm i -g @angular/cli
COPY package*.json ./

RUN npm ci
COPY . .
RUN ng build --configuration production

EXPOSE 4200

FROM nginx:latest

COPY --from=build ./dist/browser/ /usr/share/nginx/html